@IssuePortal.Api_HostAddress = http://localhost:5126

### Create a new issue
POST http://localhost:5126/api/issues
Content-Type: application/json

{
  "title": "Login fungerar inte",
  "description": "Användaren kan inte logga in.",
  "projectId": 1
}